version: "3"
services:
  tennis_model: #docker run --rm -it -v ${PWD}:/work -w /work -p 5003:5000 aimvector/python:1.0.0 /bin/sh
    container_name: tennis_model
    image: ken/tennis_model:1.0.0
    build: ./app
    working_dir: /work
    entrypoint: /bin/sh
    #command: python app.py
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./app/source/:/work